version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: database_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database_name"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Weaviate 벡터 데이터베이스
  weaviate:
    image: semitechnologies/weaviate:1.22.4
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 백엔드 API 서버
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://username:password@postgres:5432/database_name
      WEAVIATE_URL: http://weaviate:8080
      LLM_MODEL: microsoft/DialoGPT-medium
      MAX_TOKENS: 512
      TEMPERATURE: 0.7
      TOP_P: 0.9
      TENSOR_PARALLEL_SIZE: 1
      GPU_MEMORY_UTILIZATION: 0.9
      # OPENAI_API_KEY: your_openai_key_here  # 필요시 주석 해제
    depends_on:
      postgres:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./model:/app/model  # 모델 디렉토리 마운트
    restart: unless-stopped

  # 프론트엔드 웹 서버
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  weaviate_data: 